/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexion.Cliente;
import datos.BaseDeDatosKardex;
import dominio.Kardex;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Invitado
 */
public class MainForm extends javax.swing.JFrame implements GUIObserver {

    private final Cliente clienteServer;
    private BaseDeDatosKardex lstKardex;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.clienteServer = new Cliente(this);
        lstKardex = new BaseDeDatosKardex();
        lstKardex.inicializarKardex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstruccion = new javax.swing.JLabel();
        lblTituloRecibido = new javax.swing.JLabel();
        txtRecibido = new javax.swing.JTextField();
        btnConectarServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInstruccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccion.setText("Sistema Kardex");

        lblTituloRecibido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloRecibido.setText("Recibido:");

        btnConectarServer.setText("Conectar a servidor");
        btnConectarServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloRecibido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnConectarServer)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstruccion)
                .addGap(18, 18, 18)
                .addComponent(btnConectarServer)
                .addGap(42, 42, 42)
                .addComponent(lblTituloRecibido)
                .addGap(18, 18, 18)
                .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarServerActionPerformed
        new Thread(clienteServer).start();    }//GEN-LAST:event_btnConectarServerActionPerformed

    @Override
    public void update(String contenido) {
        txtRecibido.setText(contenido);
        clienteServer.enviar(buscarKardex(contenido));
    }

    private String buscarKardex(String alumno) {
        Kardex kardex=new Kardex(alumno.split("\\.")[0]);
        return lstKardex.getLstKardex().get(lstKardex.getLstKardex().indexOf(kardex)).toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarServer;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblTituloRecibido;
    private javax.swing.JTextField txtRecibido;
    // End of variables declaration//GEN-END:variables
}
